import 'package:bodylog/services/language_provider.dart';
import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'account': 'Account',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'preferences': 'Preferences',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'units': 'Units',
      'app_info_support': 'App Info & Support',
      'help_support_center': 'Help and Support Center',
      'about': 'About',
      'rate_us': 'Rate Us',
      'delete_account': 'Delete Account',
      'log_out': 'Log Out',
      'save': 'Save',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'leave_comment': 'Leave a comment...',
      'thank_you_rating': 'Thank you for rating us!',
      'confirm_deletion': 'Confirm Deletion',
      'delete_account_warning':
      'Are you sure you want to delete your account? This action cannot be undone.',
      'delete': 'Delete',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'password_min_6': 'Password must be at least 6 characters',
      'password_not_match': 'Passwords do not match',
      'password_changed_successfully': 'Password changed successfully',
      'account_deleted_successfully': 'Account permanently deleted',
      'settings_saved': 'Settings saved successfully',
      'settings_save_failed': 'Settings save failed',
      'about_bodylog': 'About BodyLog',
      'about_bodylog_para_1':
      'Welcome to BodyLog, your companion for tracking fitness progress, health metrics, and goals.',
      'about_bodylog_para_2':
      'BodyLog helps you stay consistent with workouts, monitor BMI and calories, and build healthier routines.',
      'about_footer': 'Developed with ❤️ for the fitness community.',
      'dashboard': 'Dashboard',
      'welcome_back': 'Welcome back,',
      'today_overview': 'Today Overview',
      'workouts': 'workouts',
      'minutes_short': 'min',
      'progress': 'Progress',
      'health': 'Health',
      'training_load': 'Training Load',
      'goal_status': 'Goal Status',
      'body_metrics': 'Body Metrics',
      'profile_snapshot': 'Profile Snapshot',
      'total_workout_minutes_this_week': 'Total workout minutes this week',
      'goals_completed': 'goals completed',
      'bmi_not_available': 'BMI not available',
      'bmi_label': 'BMI',
      'height': 'Height',
      'weight': 'Weight',
      'age': 'Age',
      'male': 'Male',
      'female': 'Female',
      'profile': 'Profile',
      'username': 'Username',
      'full_name': 'Full Name',
      'gender': 'Gender',
      'height_cm': 'Height (cm)',
      'weight_kg': 'Weight (kg)',
      'save_profile': 'Save Profile',
      'profile_updated_successfully': 'Profile updated successfully',
      'failed_to_load_profile': 'Failed to load profile',
      'failed_to_update_profile': 'Failed to update profile',
      'logout_failed': 'Logout failed',
      'username_required': 'Username is required',
      'name_alpha_only': 'Alphabetical characters and spaces only',
      'age_validation': 'Age must be an integer between 12 and 99',
      'height_validation': 'Please enter a valid height (100 - 300 cm)',
      'weight_validation': 'Please enter a valid weight (50 - 500 kg)',
      'profile_photo': 'Profile Photo',
      'take_photo': 'Take Photo',
      'choose_gallery': 'Choose from Gallery',
      'remove_photo': 'Remove Photo',
      'failed_to_pick_image': 'Failed to pick image',
      'my_goals': 'My Goals',
      'goals_subtitle': 'Set fitness goals and track your progress.',
      'goals_overview': 'Goals Overview',
      'active': 'Active',
      'completed': 'Completed',
      'progress_percent': 'Progress',
      'set_first_goal':
      'Set your first goal and start tracking your progress.',
      'add_goal': 'Add Goal',
      'create_goal': 'Create Goal',
      'edit_goal': 'Edit Goal',
      'goal_type': 'Goal Type',
      'target_value': 'Target Value',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'status': 'Status',
      'update_goal': 'Update Goal',
      'goal_created_successfully': 'Goal created successfully',
      'goal_updated_successfully': 'Goal updated successfully',
      'goal_deleted_successfully': 'Goal deleted successfully',
      'please_enter_valid_target': 'Please enter a valid target value',
      'operation_failed': 'Operation failed',
      'workouts_per_week': 'Workouts per Week',
      'calories_per_week': 'Calories per Week',
      'minutes_per_week': 'Minutes per Week',
      'weight_target': 'Weight Target',
      'target': 'Target',
      'current': 'Current',
      'complete': 'complete',
      'great_job_goal_completed': 'Great job! Goal completed.',
      'almost_there': 'Almost there. Keep going!',
      'doing_well': 'You are doing well. Stay consistent.',
      'nice_start': 'Nice start. Keep building momentum.',
      'start_today': 'Start today and build your progress.',
      'health_tracking': 'Health Tracking',
      'your_health_summary': 'Your health summary',
      'health_summary_subtitle':
      'BMI, calorie needs, and profile-based health insights.',
      'health_overview': 'Health Overview',
      'daily_calories': 'Daily Calories',
      'bmi_calculator': 'BMI Calculator',
      'calories_calculator': 'Calories Calculator',
      'category': 'Category',
      'activity_level': 'Activity Level',
      'bmr': 'BMR',
      'estimated_daily_calories': 'Estimated Daily Calories',
      'health_tips': 'Health Tips',
      'update_profile_data': 'Update Profile Data',
      'profile_data_updated_successfully':
      'Profile data updated successfully',
      'failed_to_update_profile_data': 'Failed to update profile data',
      'underweight': 'Underweight',
      'normal': 'Normal',
      'overweight': 'Overweight',
      'obese': 'Obese',
      'not_enough_data': 'Not enough data',
      'sedentary': 'Sedentary',
      'lightly_active': 'Lightly Active',
      'moderately_active': 'Moderately Active',
      'very_active': 'Very Active',
      'health_tip_missing':
      'Complete your profile data to get a more accurate health summary.',
      'health_tip_underweight':
      'Your BMI is below the normal range. Consider focusing on balanced nutrition and strength-building habits.',
      'health_tip_normal':
      'Your BMI is within the normal range. Maintain your routine with regular exercise and balanced eating.',
      'health_tip_overweight':
      'Your BMI is slightly above the normal range. A steady workout routine and calorie awareness may help.',
      'health_tip_obese':
      'Your BMI is in the high range. Consider a sustainable fitness plan, healthy meals, and regular progress tracking.',
    },
    'ms': {
      'settings': 'Tetapan',
      'account': 'Akaun',
      'edit_profile': 'Sunting Profil',
      'change_password': 'Tukar Kata Laluan',
      'preferences': 'Keutamaan',
      'dark_mode': 'Mod Gelap',
      'language': 'Bahasa',
      'units': 'Unit',
      'app_info_support': 'Maklumat Aplikasi & Sokongan',
      'help_support_center': 'Pusat Bantuan dan Sokongan',
      'about': 'Mengenai',
      'rate_us': 'Nilaikan Kami',
      'delete_account': 'Padam Akaun',
      'log_out': 'Log Keluar',
      'save': 'Simpan',
      'submit': 'Hantar',
      'cancel': 'Batal',
      'leave_comment': 'Tinggalkan komen...',
      'thank_you_rating': 'Terima kasih kerana menilai kami!',
      'confirm_deletion': 'Sahkan Pemadaman',
      'delete_account_warning':
      'Adakah anda pasti mahu memadamkan akaun anda? Tindakan ini tidak boleh dibatalkan.',
      'delete': 'Padam',
      'new_password': 'Kata Laluan Baru',
      'confirm_password': 'Sahkan Kata Laluan',
      'password_min_6': 'Kata laluan mesti sekurang-kurangnya 6 aksara',
      'password_not_match': 'Kata laluan tidak sepadan',
      'password_changed_successfully': 'Kata laluan berjaya ditukar',
      'account_deleted_successfully': 'Akaun dipadam selamanya',
      'settings_saved': 'Tetapan berjaya disimpan',
      'settings_save_failed': 'Gagal menyimpan tetapan',
      'about_bodylog': 'Mengenai BodyLog',
      'about_bodylog_para_1':
      'Selamat datang ke BodyLog, teman anda untuk menjejak kemajuan kecergasan, metrik kesihatan dan matlamat.',
      'about_bodylog_para_2':
      'BodyLog membantu anda kekal konsisten dengan senaman, memantau BMI dan kalori, serta membina rutin yang lebih sihat.',
      'about_footer': 'Dibangunkan dengan ❤️ untuk komuniti kecergasan.',
      'dashboard': 'Papan Pemuka',
      'welcome_back': 'Selamat kembali,',
      'today_overview': 'Ringkasan Hari Ini',
      'workouts': 'senaman',
      'minutes_short': 'min',
      'progress': 'Kemajuan',
      'health': 'Kesihatan',
      'training_load': 'Beban Latihan',
      'goal_status': 'Status Matlamat',
      'body_metrics': 'Metrik Badan',
      'profile_snapshot': 'Ringkasan Profil',
      'total_workout_minutes_this_week': 'Jumlah minit senaman minggu ini',
      'goals_completed': 'matlamat selesai',
      'bmi_not_available': 'BMI tidak tersedia',
      'bmi_label': 'BMI',
      'height': 'Tinggi',
      'weight': 'Berat',
      'age': 'Umur',
      'male': 'Lelaki',
      'female': 'Perempuan',
      'profile': 'Profil',
      'username': 'Nama Pengguna',
      'full_name': 'Nama Penuh',
      'gender': 'Jantina',
      'height_cm': 'Tinggi (cm)',
      'weight_kg': 'Berat (kg)',
      'save_profile': 'Simpan Profil',
      'profile_updated_successfully': 'Profil berjaya dikemas kini',
      'failed_to_load_profile': 'Gagal memuatkan profil',
      'failed_to_update_profile': 'Gagal mengemas kini profil',
      'logout_failed': 'Gagal log keluar',
      'username_required': 'Nama pengguna diperlukan',
      'name_alpha_only': 'Huruf dan ruang sahaja dibenarkan',
      'age_validation': 'Umur mestilah integer antara 12 hingga 99',
      'height_validation': 'Masukkan tinggi yang sah (100 - 300 cm)',
      'weight_validation': 'Masukkan berat yang sah (50 - 500 kg)',
      'profile_photo': 'Foto Profil',
      'take_photo': 'Ambil Foto',
      'choose_gallery': 'Pilih dari Galeri',
      'remove_photo': 'Buang Foto',
      'failed_to_pick_image': 'Gagal memilih imej',
      'my_goals': 'Matlamat Saya',
      'goals_subtitle': 'Tetapkan matlamat kecergasan dan jejak kemajuan anda.',
      'goals_overview': 'Ringkasan Matlamat',
      'active': 'Aktif',
      'completed': 'Selesai',
      'progress_percent': 'Kemajuan',
      'set_first_goal':
      'Tetapkan matlamat pertama anda dan mula menjejak kemajuan.',
      'add_goal': 'Tambah Matlamat',
      'create_goal': 'Cipta Matlamat',
      'edit_goal': 'Sunting Matlamat',
      'goal_type': 'Jenis Matlamat',
      'target_value': 'Nilai Sasaran',
      'start_date': 'Tarikh Mula',
      'end_date': 'Tarikh Tamat',
      'status': 'Status',
      'update_goal': 'Kemas Kini Matlamat',
      'goal_created_successfully': 'Matlamat berjaya dicipta',
      'goal_updated_successfully': 'Matlamat berjaya dikemas kini',
      'goal_deleted_successfully': 'Matlamat berjaya dipadam',
      'please_enter_valid_target': 'Sila masukkan nilai sasaran yang sah',
      'operation_failed': 'Operasi gagal',
      'workouts_per_week': 'Senaman Seminggu',
      'calories_per_week': 'Kalori Seminggu',
      'minutes_per_week': 'Minit Seminggu',
      'weight_target': 'Sasaran Berat',
      'target': 'Sasaran',
      'current': 'Semasa',
      'complete': 'selesai',
      'great_job_goal_completed': 'Syabas! Matlamat selesai.',
      'almost_there': 'Hampir sampai. Teruskan!',
      'doing_well': 'Anda sedang melakukannya dengan baik. Terus konsisten.',
      'nice_start': 'Permulaan yang baik. Teruskan momentum.',
      'start_today': 'Mulakan hari ini dan bina kemajuan anda.',
      'health_tracking': 'Penjejakan Kesihatan',
      'your_health_summary': 'Ringkasan kesihatan anda',
      'health_summary_subtitle':
      'BMI, keperluan kalori, dan pandangan kesihatan berdasarkan profil.',
      'health_overview': 'Ringkasan Kesihatan',
      'daily_calories': 'Kalori Harian',
      'bmi_calculator': 'Kalkulator BMI',
      'calories_calculator': 'Kalkulator Kalori',
      'category': 'Kategori',
      'activity_level': 'Tahap Aktiviti',
      'bmr': 'BMR',
      'estimated_daily_calories': 'Anggaran Kalori Harian',
      'health_tips': 'Tips Kesihatan',
      'update_profile_data': 'Kemas Kini Data Profil',
      'profile_data_updated_successfully':
      'Data profil berjaya dikemas kini',
      'failed_to_update_profile_data': 'Gagal mengemas kini data profil',
      'underweight': 'Kurang Berat',
      'normal': 'Normal',
      'overweight': 'Berat Berlebihan',
      'obese': 'Obes',
      'not_enough_data': 'Data tidak mencukupi',
      'sedentary': 'Tidak Aktif',
      'lightly_active': 'Sedikit Aktif',
      'moderately_active': 'Sederhana Aktif',
      'very_active': 'Sangat Aktif',
      'health_tip_missing':
      'Lengkapkan data profil anda untuk mendapatkan ringkasan kesihatan yang lebih tepat.',
      'health_tip_underweight':
      'BMI anda berada di bawah julat normal. Pertimbangkan pemakanan seimbang dan pembinaan kekuatan.',
      'health_tip_normal':
      'BMI anda berada dalam julat normal. Kekalkan rutin dengan senaman berkala dan pemakanan seimbang.',
      'health_tip_overweight':
      'BMI anda sedikit melebihi julat normal. Rutin senaman yang konsisten dan kesedaran kalori boleh membantu.',
      'health_tip_obese':
      'BMI anda berada dalam julat tinggi. Pertimbangkan pelan kecergasan yang mampan, makanan sihat dan penjejakan berkala.',
    },
    'zh': {
      'settings': '设置',
      'account': '账户',
      'edit_profile': '编辑资料',
      'change_password': '修改密码',
      'preferences': '偏好设置',
      'dark_mode': '深色模式',
      'language': '语言',
      'units': '单位',
      'app_info_support': '应用信息与支持',
      'help_support_center': '帮助与支持中心',
      'about': '关于',
      'rate_us': '给我们评分',
      'delete_account': '删除账户',
      'log_out': '登出',
      'save': '保存',
      'submit': '提交',
      'cancel': '取消',
      'leave_comment': '留下评论...',
      'thank_you_rating': '感谢您的评分！',
      'confirm_deletion': '确认删除',
      'delete_account_warning': '您确定要删除账户吗？此操作无法撤销。',
      'delete': '删除',
      'new_password': '新密码',
      'confirm_password': '确认密码',
      'password_min_6': '密码至少需要 6 个字符',
      'password_not_match': '两次输入的密码不一致',
      'password_changed_successfully': '密码修改成功',
      'account_deleted_successfully': '账户已永久删除',
      'settings_saved': '设置已成功保存',
      'settings_save_failed': '设置保存失败',
      'about_bodylog': '关于 BodyLog',
      'about_bodylog_para_1': '欢迎使用 BodyLog，帮助您追踪健身进度、健康指标和目标。',
      'about_bodylog_para_2': 'BodyLog 帮助您坚持锻炼、监测 BMI 与卡路里，并建立更健康的习惯。',
      'about_footer': '为健身社群用心打造 ❤️',
      'dashboard': '仪表板',
      'welcome_back': '欢迎回来，',
      'today_overview': '今日概览',
      'workouts': '训练',
      'minutes_short': '分',
      'progress': '进度',
      'health': '健康',
      'training_load': '训练负荷',
      'goal_status': '目标状态',
      'body_metrics': '身体指标',
      'profile_snapshot': '个人资料概览',
      'total_workout_minutes_this_week': '本周总训练分钟数',
      'goals_completed': '个目标已完成',
      'bmi_not_available': 'BMI 不可用',
      'bmi_label': 'BMI',
      'height': '身高',
      'weight': '体重',
      'age': '年龄',
      'male': '男',
      'female': '女',
      'profile': '个人资料',
      'username': '用户名',
      'full_name': '全名',
      'gender': '性别',
      'height_cm': '身高 (cm)',
      'weight_kg': '体重 (kg)',
      'save_profile': '保存资料',
      'profile_updated_successfully': '资料更新成功',
      'failed_to_load_profile': '加载资料失败',
      'failed_to_update_profile': '更新资料失败',
      'logout_failed': '登出失败',
      'username_required': '用户名为必填项',
      'name_alpha_only': '只能输入字母和空格',
      'age_validation': '年龄必须是 12 到 99 之间的整数',
      'height_validation': '请输入有效身高 (100 - 300 cm)',
      'weight_validation': '请输入有效体重 (50 - 500 kg)',
      'profile_photo': '头像照片',
      'take_photo': '拍照',
      'choose_gallery': '从相册选择',
      'remove_photo': '移除照片',
      'failed_to_pick_image': '选择图片失败',
      'my_goals': '我的目标',
      'goals_subtitle': '设定健身目标并追踪您的进度。',
      'goals_overview': '目标概览',
      'active': '进行中',
      'completed': '已完成',
      'progress_percent': '进度',
      'set_first_goal': '设定您的第一个目标并开始追踪进度。',
      'add_goal': '添加目标',
      'create_goal': '创建目标',
      'edit_goal': '编辑目标',
      'goal_type': '目标类型',
      'target_value': '目标数值',
      'start_date': '开始日期',
      'end_date': '结束日期',
      'status': '状态',
      'update_goal': '更新目标',
      'goal_created_successfully': '目标创建成功',
      'goal_updated_successfully': '目标更新成功',
      'goal_deleted_successfully': '目标删除成功',
      'please_enter_valid_target': '请输入有效的目标数值',
      'operation_failed': '操作失败',
      'workouts_per_week': '每周训练次数',
      'calories_per_week': '每周卡路里',
      'minutes_per_week': '每周分钟数',
      'weight_target': '目标体重',
      'target': '目标',
      'current': '当前',
      'complete': '已完成',
      'great_job_goal_completed': '做得好！目标已完成。',
      'almost_there': '快到了，继续加油！',
      'doing_well': '你做得很好，继续保持。',
      'nice_start': '开了个好头，继续前进。',
      'start_today': '从今天开始，建立你的进度。',
      'health_tracking': '健康追踪',
      'your_health_summary': '您的健康摘要',
      'health_summary_subtitle': 'BMI、卡路里需求和基于资料的健康分析。',
      'health_overview': '健康概览',
      'daily_calories': '每日卡路里',
      'bmi_calculator': 'BMI 计算器',
      'calories_calculator': '卡路里计算器',
      'category': '类别',
      'activity_level': '活动水平',
      'bmr': '基础代谢率',
      'estimated_daily_calories': '预计每日卡路里',
      'health_tips': '健康建议',
      'update_profile_data': '更新资料数据',
      'profile_data_updated_successfully': '资料数据更新成功',
      'failed_to_update_profile_data': '更新资料数据失败',
      'underweight': '体重过轻',
      'normal': '正常',
      'overweight': '超重',
      'obese': '肥胖',
      'not_enough_data': '数据不足',
      'sedentary': '久坐不动',
      'lightly_active': '轻度活动',
      'moderately_active': '中度活动',
      'very_active': '高度活动',
      'health_tip_missing': '请完善您的资料，以获得更准确的健康摘要。',
      'health_tip_underweight': '您的 BMI 低于正常范围。建议注重均衡饮食和力量训练。',
      'health_tip_normal': '您的 BMI 在正常范围内。请继续保持规律运动和均衡饮食。',
      'health_tip_overweight': '您的 BMI 略高于正常范围。稳定的运动和卡路里管理会有帮助。',
      'health_tip_obese': '您的 BMI 处于较高范围。建议制定可持续的健身计划、健康饮食并定期追踪。',
    },
    'es': {
      'settings': 'Ajustes',
      'account': 'Cuenta',
      'edit_profile': 'Editar Perfil',
      'change_password': 'Cambiar Contraseña',
      'preferences': 'Preferencias',
      'dark_mode': 'Modo Oscuro',
      'language': 'Idioma',
      'units': 'Unidades',
      'app_info_support': 'Información y Soporte',
      'help_support_center': 'Centro de Ayuda y Soporte',
      'about': 'Acerca de',
      'rate_us': 'Califícanos',
      'delete_account': 'Eliminar Cuenta',
      'log_out': 'Cerrar Sesión',
      'save': 'Guardar',
      'submit': 'Enviar',
      'cancel': 'Cancelar',
      'leave_comment': 'Deja un comentario...',
      'thank_you_rating': '¡Gracias por calificarnos!',
      'confirm_deletion': 'Confirmar Eliminación',
      'delete_account_warning':
      '¿Seguro que deseas eliminar tu cuenta? Esta acción no se puede deshacer.',
      'delete': 'Eliminar',
      'new_password': 'Nueva Contraseña',
      'confirm_password': 'Confirmar Contraseña',
      'password_min_6': 'La contraseña debe tener al menos 6 caracteres',
      'password_not_match': 'Las contraseñas no coinciden',
      'password_changed_successfully': 'Contraseña cambiada correctamente',
      'account_deleted_successfully': 'Cuenta eliminada permanentemente',
      'settings_saved': 'Ajustes guardados correctamente',
      'settings_save_failed': 'Error al guardar ajustes',
      'about_bodylog': 'Acerca de BodyLog',
      'about_bodylog_para_1':
      'Bienvenido a BodyLog, tu compañero para seguir el progreso físico, las métricas de salud y tus metas.',
      'about_bodylog_para_2':
      'BodyLog te ayuda a mantener la constancia en tus entrenamientos, controlar BMI y calorías, y crear hábitos más saludables.',
      'about_footer': 'Desarrollado con ❤️ para la comunidad fitness.',
      'dashboard': 'Panel',
      'welcome_back': 'Bienvenido de nuevo,',
      'today_overview': 'Resumen de Hoy',
      'workouts': 'entrenos',
      'minutes_short': 'min',
      'progress': 'Progreso',
      'health': 'Salud',
      'training_load': 'Carga de Entrenamiento',
      'goal_status': 'Estado de Metas',
      'body_metrics': 'Métricas Corporales',
      'profile_snapshot': 'Resumen del Perfil',
      'total_workout_minutes_this_week':
      'Total de minutos de entrenamiento esta semana',
      'goals_completed': 'metas completadas',
      'bmi_not_available': 'BMI no disponible',
      'bmi_label': 'BMI',
      'height': 'Altura',
      'weight': 'Peso',
      'age': 'Edad',
      'male': 'Hombre',
      'female': 'Mujer',
      'profile': 'Perfil',
      'username': 'Nombre de usuario',
      'full_name': 'Nombre completo',
      'gender': 'Género',
      'height_cm': 'Altura (cm)',
      'weight_kg': 'Peso (kg)',
      'save_profile': 'Guardar Perfil',
      'profile_updated_successfully': 'Perfil actualizado correctamente',
      'failed_to_load_profile': 'Error al cargar el perfil',
      'failed_to_update_profile': 'Error al actualizar el perfil',
      'logout_failed': 'Error al cerrar sesión',
      'username_required': 'El nombre de usuario es obligatorio',
      'name_alpha_only': 'Solo se permiten letras y espacios',
      'age_validation': 'La edad debe ser un entero entre 12 y 99',
      'height_validation': 'Ingresa una altura válida (100 - 300 cm)',
      'weight_validation': 'Ingresa un peso válido (50 - 500 kg)',
      'profile_photo': 'Foto de Perfil',
      'take_photo': 'Tomar Foto',
      'choose_gallery': 'Elegir de la Galería',
      'remove_photo': 'Eliminar Foto',
      'failed_to_pick_image': 'Error al elegir imagen',
      'my_goals': 'Mis Metas',
      'goals_subtitle': 'Define metas de fitness y sigue tu progreso.',
      'goals_overview': 'Resumen de Metas',
      'active': 'Activas',
      'completed': 'Completadas',
      'progress_percent': 'Progreso',
      'set_first_goal':
      'Define tu primera meta y empieza a seguir tu progreso.',
      'add_goal': 'Agregar Meta',
      'create_goal': 'Crear Meta',
      'edit_goal': 'Editar Meta',
      'goal_type': 'Tipo de Meta',
      'target_value': 'Valor Objetivo',
      'start_date': 'Fecha de Inicio',
      'end_date': 'Fecha de Fin',
      'status': 'Estado',
      'update_goal': 'Actualizar Meta',
      'goal_created_successfully': 'Meta creada correctamente',
      'goal_updated_successfully': 'Meta actualizada correctamente',
      'goal_deleted_successfully': 'Meta eliminada correctamente',
      'please_enter_valid_target': 'Ingresa un valor objetivo válido',
      'operation_failed': 'Operación fallida',
      'workouts_per_week': 'Entrenos por Semana',
      'calories_per_week': 'Calorías por Semana',
      'minutes_per_week': 'Minutos por Semana',
      'weight_target': 'Meta de Peso',
      'target': 'Objetivo',
      'current': 'Actual',
      'complete': 'completado',
      'great_job_goal_completed': '¡Gran trabajo! Meta completada.',
      'almost_there': 'Casi lo logras. ¡Sigue así!',
      'doing_well': 'Lo estás haciendo bien. Mantente constante.',
      'nice_start': 'Buen comienzo. Sigue avanzando.',
      'start_today': 'Empieza hoy y construye tu progreso.',
      'health_tracking': 'Seguimiento de Salud',
      'your_health_summary': 'Tu resumen de salud',
      'health_summary_subtitle':
      'BMI, necesidades calóricas e información de salud basada en tu perfil.',
      'health_overview': 'Resumen de Salud',
      'daily_calories': 'Calorías Diarias',
      'bmi_calculator': 'Calculadora BMI',
      'calories_calculator': 'Calculadora de Calorías',
      'category': 'Categoría',
      'activity_level': 'Nivel de Actividad',
      'bmr': 'TMB',
      'estimated_daily_calories': 'Calorías Diarias Estimadas',
      'health_tips': 'Consejos de Salud',
      'update_profile_data': 'Actualizar Datos del Perfil',
      'profile_data_updated_successfully':
      'Datos del perfil actualizados correctamente',
      'failed_to_update_profile_data':
      'Error al actualizar los datos del perfil',
      'underweight': 'Bajo peso',
      'normal': 'Normal',
      'overweight': 'Sobrepeso',
      'obese': 'Obesidad',
      'not_enough_data': 'Datos insuficientes',
      'sedentary': 'Sedentario',
      'lightly_active': 'Poco Activo',
      'moderately_active': 'Moderadamente Activo',
      'very_active': 'Muy Activo',
      'health_tip_missing':
      'Completa tus datos de perfil para obtener un resumen de salud más preciso.',
      'health_tip_underweight':
      'Tu BMI está por debajo del rango normal. Considera enfocarte en nutrición equilibrada y ejercicios de fuerza.',
      'health_tip_normal':
      'Tu BMI está dentro del rango normal. Mantén tu rutina con ejercicio regular y alimentación equilibrada.',
      'health_tip_overweight':
      'Tu BMI está ligeramente por encima del rango normal. Una rutina constante y el control de calorías pueden ayudar.',
      'health_tip_obese':
      'Tu BMI está en un rango alto. Considera un plan de fitness sostenible, alimentación saludable y seguimiento regular.',
    },
  };

  static String text(BuildContext context, String key) {
    final code = languageProvider.locale.languageCode;
    return _localizedValues[code]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
